name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/DrumScript
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv 
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          uv pip install --system build twine

      - name: Build package
        run: python -m build

      - name: Check if package version exists on PyPI
        id: package_exists
        run: |
          package_name="drumscript"
          version=$(grep -Po "(?<=version=').*(?=')" pyproject.toml)
          response=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/pypi/$package_name/$version/json)
          if [ "$response" = "200" ]; then
            echo "Package version $version already exists on PyPI"
            echo "package_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Package version $version does not exist on PyPI"
            echo "package_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish package distributions to PyPI
        if: steps.package_exists.outputs.package_exists == 'false'
              - name: Check if package version exists on PyPI
        id: package_exists
        run: |
          package_name="drumscript"
          version=$(grep -Po "(?<=version=').*(?=')" pyproject.toml)
          response=$(curl -s -o /dev/null -w "%{http_code}" https://pypi.org/pypi/$package_name/$version/json)
          if [ "$response" = "200" ]; then
            echo "Package version $version already exists on PyPI"
            echo "package_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Package version $version does not exist on PyPI" 
            echo "package_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish package distributions to PyPI
        if: steps.package_exists.outputs.package_exists == 'false'  
        uses: pypa/gh-action-pypi-publish@release/v1