# blank_issues_enabled: true
# contact_links:
  #- name: Community Q&A
  #  url: https://github.com/DrumScript/DrumScript/discussions
  #  about: Please ask and answer questions here rather than raising an issue.